import os

from conan import ConanFile
from conan.errors import ConanInvalidConfiguration
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import copy, get, rmdir

required_conan_version = ">=2.0"


class ScotchConan(ConanFile):
    name = "scotch"
    description = (
        "Scotch and PT-Scotch: graph partitioning, graph clustering and sparse matrix "
        "ordering, sequential and MPI-parallel"
    )
    license = "CECILL-C"
    url = "https://gitlab.inria.fr/scotch/scotch"
    homepage = "https://www.labri.fr/perso/pelegrin/scotch/"
    topics = ("graph-partitioning", "mesh-partitioning", "sparse-matrix-ordering", "hpc", "mpi")
    package_type = "library"

    settings = "os", "arch", "compiler", "build_type"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "with_ptscotch": [True, False],
        "integer_size": ["default", "32", "64"],
        "with_threads": [True, False],
        "with_zlib": [True, False],
        "with_bzip2": [True, False],
        "with_lzma": [True, False],
    }
    default_options = {
        "shared": True,
        "fPIC": True,
        "with_ptscotch": True,
        "integer_size": "default",
        "with_threads": True,
        "with_zlib": True,
        "with_bzip2": False,
        "with_lzma": False,
    }

    def config_options(self):
        if self.settings.os == "Windows":
            self.options.rm_safe("fPIC")

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")
        # Pure C library.
        self.settings.rm_safe("compiler.libcxx")
        self.settings.rm_safe("compiler.cppstd")
        if self.options.with_ptscotch:
            # Open MPI's static archives define the MPI_* entry points as weak symbols,
            # so a shared library linking libmpi.a does not pull them in and is left
            # with undefined MPI symbols plus a partial copy of the profiling wrappers.
            self.options["openmpi"].shared = True

    def layout(self):
        cmake_layout(self, src_folder="src")

    def requirements(self):
        if self.options.with_ptscotch:
            # ptscotch.h includes <mpi.h> and its API takes MPI_Comm arguments.
            self.requires("openmpi/[>=4.1 <5]", transitive_headers=True, transitive_libs=True)
        if self.options.with_zlib:
            self.requires("zlib/[>=1.2.11 <2]")
        if self.options.with_bzip2:
            self.requires("bzip2/[>=1.0.8 <2]")
        if self.options.with_lzma:
            self.requires("xz_utils/[>=5.4.5 <6]")

    def build_requirements(self):
        # Upstream ships pre-generated parser and lexer files as a fallback, but warns
        # they may not work; regenerate them with the versions it asks for instead.
        self.tool_requires("bison/[>=3.8.2 <4]")
        self.tool_requires("flex/[>=2.6.4 <3]")

    def validate(self):
        if self.options.with_ptscotch and self.settings.os == "Windows":
            raise ConanInvalidConfiguration(
                f"{self.ref} with with_ptscotch=True is not supported on Windows: no MPI "
                "package is available for it. Use '-o scotch/*:with_ptscotch=False'."
            )

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)

    def generate(self):
        CMakeDeps(self).generate()

        tc = CMakeToolchain(self)
        tc.cache_variables["BUILD_FORTRAN"] = False
        tc.cache_variables["BUILD_PTSCOTCH"] = bool(self.options.with_ptscotch)
        tc.cache_variables["BUILD_LIBESMUMPS"] = False
        # libscotchmetis installs its own metis.h/parmetis.h, which would shadow the real
        # METIS headers of anything that uses both.
        tc.cache_variables["BUILD_LIBSCOTCHMETIS"] = False
        tc.cache_variables["INSTALL_METIS_HEADERS"] = False
        tc.cache_variables["ENABLE_TESTS"] = False
        tc.cache_variables["THREADS"] = bool(self.options.with_threads)
        # Checking for MPI_THREAD_MULTIPLE compiles a probe with mpicc and runs it with
        # mpiexec during configure. A PT-Scotch built with it also requires every caller
        # to initialise MPI with MPI_THREAD_MULTIPLE, which most applications do not.
        tc.cache_variables["MPI_THREAD_MULTIPLE"] = False
        tc.cache_variables["USE_ZLIB"] = bool(self.options.with_zlib)
        tc.cache_variables["USE_BZ2"] = bool(self.options.with_bzip2)
        tc.cache_variables["USE_LZMA"] = bool(self.options.with_lzma)
        if self.options.integer_size != "default":
            tc.cache_variables["INTSIZE"] = str(self.options.integer_size)
        if self.options.with_ptscotch:
            # Scotch reads these two FindMPI results, which the MPI config generated by
            # CMakeDeps does not set: it aborts without MPI_C_FOUND and runs a regex on
            # the version string to pick mpiexec flags for its (disabled) tests.
            tc.cache_variables["MPI_C_FOUND"] = True
            tc.cache_variables["MPI_C_LIBRARY_VERSION_STRING"] = (
                f"Open MPI v{self.dependencies['openmpi'].ref.version}"
            )
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        for license_file in ("LICENSE_en.txt", "LICENCE_fr.txt"):
            copy(
                self,
                license_file,
                src=self.source_folder,
                dst=os.path.join(self.package_folder, "licenses"),
            )
        cmake = CMake(self)
        cmake.install()
        # Upstream's CMake package files are replaced by the ones CMakeDeps generates.
        rmdir(self, os.path.join(self.package_folder, "lib", "cmake"))
        rmdir(self, os.path.join(self.package_folder, "share"))

    def package_info(self):
        self.cpp_info.set_property("cmake_file_name", "SCOTCH")

        system_libs = []
        if self.settings.os in ("Linux", "FreeBSD"):
            system_libs.append("m")
            if self.options.with_threads:
                system_libs.append("pthread")

        # libscotch leaves its error handlers (SCOTCH_errorPrint and friends) to the
        # application: either one of its own, or scotcherr (print and return) or
        # scotcherrexit (print and exit). scotcherr is the default here; a consumer that
        # wants scotcherrexit links that component as well, ahead of scotch.
        for err in ("scotcherr", "scotcherrexit"):
            self.cpp_info.components[err].set_property("cmake_target_name", f"SCOTCH::{err}")
            self.cpp_info.components[err].libs = [err]

        scotch = self.cpp_info.components["libscotch"]
        scotch.set_property("cmake_target_name", "SCOTCH::scotch")
        scotch.libs = ["scotch"]
        scotch.system_libs = system_libs
        scotch.requires = ["scotcherr"]
        if self.options.with_zlib:
            scotch.requires.append("zlib::zlib")
        if self.options.with_bzip2:
            scotch.requires.append("bzip2::bzip2")
        if self.options.with_lzma:
            scotch.requires.append("xz_utils::xz_utils")

        if self.options.with_ptscotch:
            for err in ("ptscotcherr", "ptscotcherrexit"):
                self.cpp_info.components[err].set_property("cmake_target_name", f"SCOTCH::{err}")
                self.cpp_info.components[err].libs = [err]
                self.cpp_info.components[err].requires = ["openmpi::ompi-c"]

            ptscotch = self.cpp_info.components["libptscotch"]
            ptscotch.set_property("cmake_target_name", "SCOTCH::ptscotch")
            ptscotch.libs = ["ptscotch"]
            ptscotch.system_libs = system_libs
            # Only the MPI C component: the openmpi package as a whole also carries
            # libompitrace, whose PMPI wrappers print a trace line for every MPI call.
            ptscotch.requires = ["libscotch", "ptscotcherr", "openmpi::ompi-c"]
