import os
import textwrap

from conan import ConanFile
from conan.errors import ConanInvalidConfiguration
from conan.tools.build import check_min_cppstd
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import collect_libs, copy, get, rmdir, save


class CasadiConan(ConanFile):
    name = "casadi"
    description = (
        "CasADi is a symbolic framework for algorithmic differentiation and numeric "
        "optimization, aimed at nonlinear optimal control"
    )
    license = "LGPL-3.0-or-later"
    url = "https://github.com/casadi/casadi"
    homepage = "https://web.casadi.org"
    topics = ("symbolic", "automatic-differentiation", "optimization", "optimal-control", "nlp")
    package_type = "library"

    settings = "os", "arch", "compiler", "build_type"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "with_openmp": [True, False],
        "with_thread": [True, False],
        "with_lapack": [True, False],
        "with_qpoases": [True, False],
        "with_sundials": [True, False],
        "with_csparse": [True, False],
        "with_tinyxml": [True, False],
    }
    default_options = {
        "shared": True,
        "fPIC": True,
        "with_openmp": False,
        "with_thread": True,
        "with_lapack": False,
        "with_qpoases": False,
        # Bundled sources, built by casadi itself; these are the upstream defaults.
        "with_sundials": True,
        "with_csparse": True,
        "with_tinyxml": True,
    }

    def config_options(self):
        if self.settings.os == "Windows":
            self.options.rm_safe("fPIC")

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")

    def requirements(self):
        if self.options.with_lapack:
            self.requires("openblas/[>=0.3.24 <1]")

    def validate(self):
        check_min_cppstd(self, 11)
        if self.options.with_qpoases and not self.options.with_lapack:
            raise ConanInvalidConfiguration(
                f"{self.ref} with with_qpoases=True requires with_lapack=True: qpOASES is "
                "built against LAPACK for its dense linear algebra."
            )
        if self.options.with_lapack and not self.dependencies["openblas"].options.build_lapack:
            raise ConanInvalidConfiguration(
                f"{self.ref} with with_lapack=True requires '-o openblas/*:build_lapack=True'"
            )

    def layout(self):
        cmake_layout(self, src_folder="src")

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)

    def _write_lapack_config(self):
        # casadi resolves LAPACK with find_package(LAPACK REQUIRED), which would search
        # the machine instead of the Conan dependency graph. Conan's toolchain prefers
        # config mode, so hand LAPACK to CMake as a package config forwarding to the
        # OpenBLAS target generated by CMakeDeps.
        content = textwrap.dedent("""\
            find_package(OpenBLAS REQUIRED CONFIG)
            if(NOT TARGET LAPACK::LAPACK)
              add_library(LAPACK::LAPACK INTERFACE IMPORTED)
              set_target_properties(LAPACK::LAPACK PROPERTIES
                INTERFACE_LINK_LIBRARIES OpenBLAS::OpenBLAS)
            endif()
            set(LAPACK_LIBRARIES OpenBLAS::OpenBLAS)
            set(LAPACK_INCLUDE_DIRS "${OpenBLAS_INCLUDE_DIRS}")
            set(LAPACK_FOUND TRUE)
            """)
        # Both spellings CMake accepts, so the lookup does not depend on case.
        save(self, os.path.join(self.generators_folder, "LAPACKConfig.cmake"), content)
        save(self, os.path.join(self.generators_folder, "lapack-config.cmake"), content)

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
        if self.options.with_lapack:
            self._write_lapack_config()

        tc = CMakeToolchain(self)
        # casadi has its own pair of switches instead of BUILD_SHARED_LIBS.
        tc.cache_variables["ENABLE_SHARED"] = bool(self.options.shared)
        tc.cache_variables["ENABLE_STATIC"] = not self.options.shared
        # Keep the install tree free of absolute build machine paths.
        tc.cache_variables["RELOCATABLE"] = True
        # casadi.hpp alone is not enough for the usual extension points (Callback
        # subclasses, custom linear solvers), which include headers upstream treats as
        # internal and does not install by default.
        tc.cache_variables["INSTALL_INTERNAL_HEADERS"] = True

        tc.cache_variables["WITH_OPENMP"] = bool(self.options.with_openmp)
        tc.cache_variables["WITH_THREAD"] = bool(self.options.with_thread)
        tc.cache_variables["WITH_LAPACK"] = bool(self.options.with_lapack)
        tc.cache_variables["WITH_QPOASES"] = bool(self.options.with_qpoases)
        tc.cache_variables["WITH_SUNDIALS"] = bool(self.options.with_sundials)
        tc.cache_variables["WITH_CSPARSE"] = bool(self.options.with_csparse)
        tc.cache_variables["WITH_TINYXML"] = bool(self.options.with_tinyxml)

        # Sundials, CSparse and TinyXML ship inside the casadi tarball; build those
        # copies rather than looking for system ones.
        tc.cache_variables["WITH_BUILD_SUNDIALS"] = bool(self.options.with_sundials)
        tc.cache_variables["WITH_BUILD_CSPARSE"] = bool(self.options.with_csparse)
        tc.cache_variables["WITH_BUILD_TINYXML"] = bool(self.options.with_tinyxml)

        # Every WITH_BUILD_<pkg> switch makes the build clone and compile a dependency
        # from the network at build time, which a Conan package must never do. The ones
        # above are the exception: they compile sources already present in the tarball.
        tc.cache_variables["WITH_BUILD_REQUIRED"] = False
        tc.cache_variables["WITH_BUILD_LAPACK"] = False

        tc.cache_variables["WITH_EXAMPLES"] = False
        tc.cache_variables["WITH_DOC"] = False
        tc.cache_variables["WITH_PYTHON"] = False
        tc.cache_variables["WITH_MATLAB"] = False
        tc.cache_variables["WITH_OCTAVE"] = False
        tc.cache_variables["WITH_JSON"] = False
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        copy(
            self,
            "LICENSE.txt",
            src=self.source_folder,
            dst=os.path.join(self.package_folder, "licenses"),
        )
        cmake = CMake(self)
        cmake.install()
        # Upstream's CMake package files describe only the upstream layout; CMakeDeps
        # generates correct ones for consumers instead.
        rmdir(self, os.path.join(self.package_folder, "lib", "cmake"))
        rmdir(self, os.path.join(self.package_folder, "lib", "pkgconfig"))
        rmdir(self, os.path.join(self.package_folder, "share"))

    def package_info(self):
        self.cpp_info.set_property("cmake_file_name", "casadi")
        self.cpp_info.set_property("cmake_target_name", "casadi::casadi")

        if self.options.shared:
            # The plugins (casadi_nlpsol_sqpmethod, casadi_integrator_cvodes, ...) are
            # separate shared libraries that libcasadi dlopens by name at run time, so
            # consumers link the core alone.
            self.cpp_info.libs = ["casadi"]
        else:
            # Statically there is nothing to dlopen: a plugin only registers itself if
            # its archive is on the link line. Order matters for a single-pass linker,
            # so the plugins come first, then the sundials glue they share, then the
            # core they all call into.
            tail = ["casadi"]
            if self.options.with_sundials:
                tail.insert(0, "casadi_sundials_common")
            plugins = [lib for lib in collect_libs(self) if lib not in tail]
            self.cpp_info.libs = plugins + tail

        if self.settings.os in ("Linux", "FreeBSD"):
            self.cpp_info.system_libs = ["m", "dl"]
            if self.options.with_thread:
                self.cpp_info.system_libs.append("pthread")

        if self.options.with_openmp:
            openmp_flags = []
            if self.settings.compiler in ("gcc", "clang"):
                openmp_flags = ["-fopenmp"]
            elif self.settings.compiler == "apple-clang":
                openmp_flags = ["-Xpreprocessor", "-fopenmp"]
            elif self.settings.compiler == "msvc":
                openmp_flags = ["-openmp"]
            self.cpp_info.cflags += openmp_flags
            self.cpp_info.cxxflags += openmp_flags
            self.cpp_info.sharedlinkflags += openmp_flags
            self.cpp_info.exelinkflags += openmp_flags
