import os
import textwrap

from conan import ConanFile
from conan.errors import ConanInvalidConfiguration
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import copy, get, rmdir, save


class HypreConan(ConanFile):
    name = "hypre"
    description = "hypre: a library of high performance preconditioners and solvers for large sparse linear systems"
    license = "Apache-2.0 OR MIT"
    url = "https://github.com/hypre-space/hypre"
    homepage = "https://www.llnl.gov/casc/hypre"
    topics = ("linear-solvers", "preconditioners", "multigrid", "hpc", "mpi")
    package_type = "library"

    settings = "os", "arch", "compiler", "build_type"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "with_mpi": [True, False],
        "with_openmp": [True, False],
        "with_lapack": [True, False],
        "bigint": [True, False],
        "mixedint": [True, False],
    }
    default_options = {
        "shared": True,
        "fPIC": True,
        "with_mpi": True,
        "with_openmp": False,
        "with_lapack": False,
        "bigint": False,
        "mixedint": False,
    }

    def config_options(self):
        if self.settings.os == "Windows":
            self.options.rm_safe("fPIC")

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")

    def requirements(self):
        if self.options.with_mpi:
            # HYPRE.h includes <mpi.h> once the library is built with MPI.
            self.requires("openmpi/[>=4.1 <5]", transitive_headers=True)
        if self.options.with_lapack:
            self.requires("openblas/[>=0.3.24 <1]")

    def validate(self):
        if self.options.bigint and self.options.mixedint:
            raise ConanInvalidConfiguration(
                "Options 'bigint' and 'mixedint' are mutually exclusive: bigint widens both "
                "HYPRE_Int and HYPRE_BigInt, mixedint only HYPRE_BigInt."
            )
        if self.options.with_mpi and self.settings.os == "Windows":
            raise ConanInvalidConfiguration(
                f"{self.ref} with with_mpi=True is not supported on Windows: no MPI package "
                "is available for it. Use '-o hypre/*:with_mpi=False' for a serial build."
            )
        if self.options.with_lapack and not self.dependencies["openblas"].options.build_lapack:
            raise ConanInvalidConfiguration(
                f"{self.ref} with with_lapack=True requires '-o openblas/*:build_lapack=True'"
            )

    def layout(self):
        cmake_layout(self, src_folder="src")

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)

    def _write_blas_lapack_configs(self):
        # hypre resolves an external BLAS/LAPACK with find_package(BLAS/LAPACK REQUIRED),
        # which would search the machine instead of the Conan dependency graph. Conan's
        # toolchain prefers config mode, so hand both to CMake as package configs that
        # forward to the OpenBLAS target generated by CMakeDeps. Naming that target in
        # TPL_BLAS_LIBRARIES instead does not work: hypre links it without ever calling
        # find_package, so the target does not exist at generate time.
        for name in ("BLAS", "LAPACK"):
            content = textwrap.dedent(f"""\
                find_package(OpenBLAS REQUIRED CONFIG)
                if(NOT TARGET {name}::{name})
                  add_library({name}::{name} INTERFACE IMPORTED)
                  set_target_properties({name}::{name} PROPERTIES
                    INTERFACE_LINK_LIBRARIES OpenBLAS::OpenBLAS)
                endif()
                set({name}_LIBRARIES OpenBLAS::OpenBLAS)
                set({name}_INCLUDE_DIRS "${{OpenBLAS_INCLUDE_DIRS}}")
                set({name}_FOUND TRUE)
                """)
            # Both spellings CMake accepts, so the lookup does not depend on case.
            save(self, os.path.join(self.generators_folder, f"{name}Config.cmake"), content)
            save(self, os.path.join(self.generators_folder, f"{name.lower()}-config.cmake"), content)

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
        if self.options.with_lapack:
            self._write_blas_lapack_configs()

        tc = CMakeToolchain(self)
        # hypre reads its settings from the CMake cache and additionally records which
        # ones the user set explicitly (set_hypre_option tests DEFINED CACHE{...}), so
        # these have to be cache entries rather than plain variables.
        tc.cache_variables["BUILD_SHARED_LIBS"] = bool(self.options.shared)
        tc.cache_variables["HYPRE_ENABLE_MPI"] = bool(self.options.with_mpi)
        tc.cache_variables["HYPRE_ENABLE_OPENMP"] = bool(self.options.with_openmp)
        tc.cache_variables["HYPRE_ENABLE_BIGINT"] = bool(self.options.bigint)
        tc.cache_variables["HYPRE_ENABLE_MIXEDINT"] = bool(self.options.mixedint)
        tc.cache_variables["HYPRE_BUILD_EXAMPLES"] = False
        tc.cache_variables["HYPRE_BUILD_TESTS"] = False
        # Never let the build download third-party libraries of its own.
        tc.cache_variables["HYPRE_BUILD_UMPIRE"] = False

        # hypre ships a bundled BLAS/LAPACK subset and uses it by default; turning that
        # off makes it look for an external one, which _write_blas_lapack_configs points
        # at OpenBLAS.
        use_internal = not self.options.with_lapack
        tc.cache_variables["HYPRE_ENABLE_HYPRE_BLAS"] = use_internal
        tc.cache_variables["HYPRE_ENABLE_HYPRE_LAPACK"] = use_internal
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure(build_script_folder="src")
        cmake.build()

    def package(self):
        for license_file in ("LICENSE-APACHE", "LICENSE-MIT", "COPYRIGHT", "NOTICE"):
            copy(
                self,
                license_file,
                src=self.source_folder,
                dst=os.path.join(self.package_folder, "licenses"),
            )
        cmake = CMake(self)
        cmake.install()
        # Upstream's CMake package files hard-code build machine paths; CMakeDeps
        # generates correct ones for consumers instead.
        rmdir(self, os.path.join(self.package_folder, "lib", "cmake"))

    def package_info(self):
        self.cpp_info.set_property("cmake_file_name", "HYPRE")
        self.cpp_info.set_property("cmake_target_name", "HYPRE::HYPRE")

        self.cpp_info.libs = ["HYPRE"]

        if self.settings.os in ("Linux", "FreeBSD"):
            self.cpp_info.system_libs = ["m", "dl"]

        if self.options.with_openmp:
            openmp_flags = []
            if self.settings.compiler in ("gcc", "clang"):
                openmp_flags = ["-fopenmp"]
            elif self.settings.compiler == "apple-clang":
                openmp_flags = ["-Xpreprocessor", "-fopenmp"]
            elif self.settings.compiler == "msvc":
                openmp_flags = ["-openmp"]
            self.cpp_info.cflags += openmp_flags
            self.cpp_info.cxxflags += openmp_flags
            self.cpp_info.sharedlinkflags += openmp_flags
            self.cpp_info.exelinkflags += openmp_flags
